In [3]:
import pandas as pd

Creamos un Diccionario con Paises

In [1]:
dataPaises = {
    'pais': ['España', 'Francia', 'Alemania', 'Italia', 'Portugal'],
    'capital': ['Madrid', 'París', 'Berlín', 'Roma', 'Lisboa'],
    'superficie': [505992, 643801, 357022, 301340, 92090],
    'idioma': ['español', 'francés', 'alemán', 'italiano', 'portugués']
}
dataPaises

{'pais': ['España', 'Francia', 'Alemania', 'Italia', 'Portugal'],
 'capital': ['Madrid', 'París', 'Berlín', 'Roma', 'Lisboa'],
 'superficie': [505992, 643801, 357022, 301340, 92090],
 'idioma': ['español', 'francés', 'alemán', 'italiano', 'portugués']}

Creamos un Data Frame con el diccionario

In [4]:
dfpaises = pd.DataFrame(dataPaises)

dfpaises

       pais capital  superficie     idioma
0    España  Madrid      505992    español
1   Francia   París      643801    francés
2  Alemania  Berlín      357022     alemán
3    Italia    Roma      301340   italiano
4  Portugal  Lisboa       92090  portugués

Por ejemplo podemos dibujar solo una columna

In [5]:
dfpaises[['capital']]

  capital
0  Madrid
1   París
2  Berlín
3    Roma
4  Lisboa

Podemos dibujar + de una

In [6]:
dfpaises[['capital', 'idioma']]

  capital     idioma
0  Madrid    español
1   París    francés
2  Berlín     alemán
3    Roma   italiano
4  Lisboa  portugués

Se pueden seleccionar las filas por su posicion(indice)
Primero incluido el segundo no.

In [10]:
dfpaises[2:5]

       pais capital  superficie     idioma
2  Alemania  Berlín      357022     alemán
3    Italia    Roma      301340   italiano
4  Portugal  Lisboa       92090  portugués

Podemos sustituir el indice que viene por fefecto si quisieramos.

In [11]:
dfpaises.index = ['FR', 'AL', 'IT', 'PT', 'ES']
dfpaises

        pais capital  superficie     idioma
FR    España  Madrid      505992    español
AL   Francia   París      643801    francés
IT  Alemania  Berlín      357022     alemán
PT    Italia    Roma      301340   italiano
ES  Portugal  Lisboa       92090  portugués

podemos volver a crear nuevamente el indice por defecto

In [13]:
dfpaises = dfpaises.reset_index()
dfpaises

   level_0 index      pais capital  superficie     idioma
0        0    FR    España  Madrid      505992    español
1        1    AL   Francia   París      643801    francés
2        2    IT  Alemania  Berlín      357022     alemán
3        3    PT    Italia    Roma      301340   italiano
4        4    ES  Portugal  Lisboa       92090  portugués