In [3]:
import pandas as pd
import numpy as np

In [4]:

df = pd.read_csv("data/influencers.csv", index_col="id")
df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129

In [5]:

df_filtrado = df.dropna()
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,ALICANTE,sofiasantos,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,MADRID,adrianramos,389.0,258

In [6]:

df_filtrado = df.fillna(0)
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,0.0,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129

In [7]:

df_filtrado = df.fillna({ "retweets": 0, "mentions": -1 })
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,-1.0,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129

In [8]:

df[  (df["favorites"] > 400) & (df["mentions"] > 20)]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183744,Thanks man!,430.0,143.0,28.0,ALICANTE,cristianoronaldo,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,ALICANTE,cristianoronaldo,82.0,351
183746,BORED AF,488.0,28.0,27.0,ELCHE,danicarvajal,21.0,2721

In [9]:
df[df["full_text"].str.contains("programming")]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183732,Its been in love with the game with the origin...,349.0,44.0,19.0,ALICANTE,sofiasantos,982.0,1822
183745,There is nothing better than programming!,424.0,110.0,29.0,ALICANTE,cristianoronaldo,82.0,351
183747,I do not know if i like programming or other t...,318.0,58.0,20.0,ALICANTE,antoniamartinez,928.0,9918

Puedes crear funciones ... el resultado lo suelta en la columna a la que se asigna, ya sea existente o una nueva.

In [12]:
def multiplicar_por_dos(menciones):
    return menciones * 2

df["mentions_doble"] = df["mentions"].apply(multiplicar_por_dos)
df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees,mentions_doble
id,,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,MADRID,adrianramos,389.0,258,20.0
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,ALICANTE,sofiasantos,982.0,1822,NaN
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129,12.0
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378,6.0
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129,18.0

El siguiente ejemplo es enviar una fila completa del Dataframe en lugar del valor de una columna.
Se realiza indicando axis=1 al enviar la peticion. 
Vamos a dividir followees/followers para saber la popularidad de una persona en una nueva columna.

In [20]:
def popularidad(fila):
    followees = fila["followees"]
    followers = fila["followers"]
    resultado = followees/followers
    return resultado
df["popularidad"] = df.apply(popularidad, axis=1)
df.head()
df.sort_values("popularidad", ascending=False).head()

,full_text,favorites,retweets,mentions,country,user,followers,followees,mentions_doble,popularidad
id,,,,,,,,,,
183735,Buy this product NOW!!,418.0,24.0,2.0,ELCHE,danicarvajal,21.0,2721,4.0,129.571429
183738,hmmm feeling bad today,296.0,93.0,29.0,ELCHE,danicarvajal,21.0,2721,58.0,129.571429
183746,BORED AF,488.0,28.0,27.0,ELCHE,danicarvajal,21.0,2721,54.0,129.571429
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129,12.0,10.750000
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129,18.0,10.750000

In [ ]:
Tambien podemos recuperar la media de una agrupacion.

In [26]:
df.groupby(["country"]).mean(numeric_only=True)
df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees,mentions_doble,popularidad
id,,,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,MADRID,adrianramos,389.0,258,20.0,0.663239
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,ALICANTE,sofiasantos,982.0,1822,NaN,1.855397
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129,12.0,10.750000
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378,6.0,1.138554
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129,18.0,10.750000

Mediante agg nos permite utilizar varias funciones de agrupacion a la vez.

In [25]:
grupo = df.groupby(["country"]).agg({
    "followers": "sum",
    "followees": "mean",
    "retweets": "max",
})
grupo

          followers    followees  retweets
country
ALICANTE     6166.0  1889.363636     145.0
ELCHE         123.0  1101.000000     130.0
MADRID       2884.0   318.000000     146.0

Podemos exportar datos a CSV / JSON

In [28]:
grupo.to_csv("data/grupo.csv")
grupo.to_json("data/grupo.json")